name: build-push-ar
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      build-args:
        required: false
        type: string
        default: ""
      context:
        required: false
        type: string
        default: "."
      tag:
        required: false
        type: string
        default: ""
jobs:
  build-push-ar:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4

    - name: Extract branch name as docker tag
      shell: bash
      run: |-
        BRANCH=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/[^a-zA-Z0-9._-]//g' | awk '{print substr($0, length($0)-120)}')
        if [ "$BRANCH" = "main" ] && [ "${{ inputs.tag }}" != "" ]; then
          BRANCH="${{ inputs.tag }}"
        fi
        echo "branch=$BRANCH" >> $GITHUB_OUTPUT
      id: extract_branch

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f' # v2
      with:
        workload_identity_provider: ${{ secrets.GCLOUD_OIDC_POOL }}
        create_credentials_file: true
        service_account: ${{ secrets.GSA }}
        token_format: 'access_token'

    - uses: 'docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772' # v3
      name: 'Docker login'
      with:
        registry: 'us-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: Build and push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        context: ${{ inputs.context }}
        push: true
        build-args: ${{ inputs.build-args }}
        tags: |
          us-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/${{ inputs.image }}:${{steps.extract_branch.outputs.branch}}
